-- Crear la base de datos (si no existe)
CREATE DATABASE IF NOT EXISTS JUEGO;

-- Usar la base de datos
USE JUEGO;


CREATE TABLE usuarios (
    id_usuario INT AUTO_INCREMENT PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL
);

CREATE TABLE palabras (
    id INT AUTO_INCREMENT PRIMARY KEY,
    palabra VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) DEFAULT 'Sin categoría'
);

CREATE TABLE partidas (
    id_partida INT AUTO_INCREMENT PRIMARY KEY,
    id_jugador INT NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    tiempo_segundos INT,
    puntaje INT, 
    FOREIGN KEY (id_jugador) REFERENCES usuarios(id_usuario)
);

INSERT INTO palabras (palabra, categoria) VALUES 
('universidad', 'Educación'),
('bicicleta', 'Transporte'),
('electricidad', 'Ciencia'),
('naturaleza', 'Medio ambiente'),
('fotografía', 'Arte'),
('programador', 'Profesión'),
('arquitectura', 'Construcción'),
('computadora', 'Tecnología'),
('matemáticas', 'Educación'),
('astronomía', 'Ciencia'),
('restaurante', 'Comida'),
('carretera', 'Transporte'),
('hospitalidad', 'Cualidad'),
('electricista', 'Profesión'),
('constructora', 'Construcción'),
('psicología', 'Ciencia'),
('universales', 'Concepto'),
('alimentación', 'Salud'),
('documentales', 'Medios'),
('maravillosa', 'Cualidad'),
('biodiversidad', 'Medio ambiente'),
('investigador', 'Profesión'),
('bibliotecas', 'Educación'),
('temperatura', 'Ciencia'),
('imaginación', 'Cualidad'),
('laboratorio', 'Ciencia'),
('construcción', 'Construcción'),
('conversación', 'Acción'),
('reproducción', 'Biología'),
('documentación', 'Administración'),
('electricista', 'Profesión'),
('aceleración', 'Física'),
('biotecnología', 'Ciencia'),
('jurisdicción', 'Ley'),
('hidratación', 'Salud'),
('experimentar', 'Acción'),
('transparente', 'Cualidad'),
('fotocopiadora', 'Oficina'),
('clasificación', 'Proceso'),
('felicidad', 'Emoción'),
('desesperación', 'Emoción'),
('características', 'Descripción'),
('conservación', 'Medio ambiente'),
('especialista', 'Profesión'),
('programación', 'Tecnología'),
('ventilación', 'Salud'),
('desarrollo', 'Proceso'),
('investigación', 'Ciencia'),
('caracterizado', 'Acción'),
('transformador', 'Tecnología'),
('comunicación', 'Acción'),
('participación', 'Proceso'),
('organización', 'Administración'),
('independencia', 'Concepto'),
('acumulación', 'Proceso'),
('importación', 'Economía'),
('exportación', 'Economía'),
('alimentaria', 'Salud'),
('especialidad', 'Profesión'),
('habitaciones', 'Hogar'),
('cancelación', 'Acción'),
('temperamento', 'Emoción'),
('biodegradable', 'Medio ambiente'),
('instrucción', 'Educación'),
('investigador', 'Profesión'),
('maravillosamente', 'Cualidad'),
('cualificación', 'Educación'),
('impresionante', 'Cualidad'),
('comportamiento', 'Psicología'),
('significativo', 'Descripción'),
('recomendación', 'Comunicación'),
('movilización', 'Acción'),
('universitaria', 'Educación'),
('desintegración', 'Física'),
('desorganizado', 'Cualidad'),
('administración', 'Profesión'),
('posibilidades', 'Concepto'),
('revolucionario', 'Historia'),
('reconocimiento', 'Acción'),
('electricamente', 'Física'),
('necesariamente', 'Concepto'),
('responsabilidad', 'Cualidad'),
('proporcionado', 'Acción'),
('reestablecimiento', 'Proceso'),
('inestabilidad', 'Cualidad'),
('funcionalidad', 'Tecnología'),
('conectividad', 'Tecnología'),
('equipamiento', 'Objeto'),
('conectividad', 'Tecnología'),
('reutilizable', 'Medio ambiente'),
('contribuyente', 'Economía'),
('digitalmente', 'Tecnología'),
('implementación', 'Proceso'),
('cooperación', 'Acción'),
('legalización', 'Ley'),
('demostración', 'Acción'),
('flexibilidad', 'Cualidad'),
('reorganización', 'Administración'),
('geopolítica', 'Ciencia'),
('intercultural', 'Educación'),
('sustitución', 'Acción'),
('transformación', 'Cambio'),
('contemporánea', 'Arte'),
('compatibilidad', 'Tecnología');
